### ISSUE TITLE
analiza date pentru mai multe orase

### ISSUE THREAD

**Issue by mcshosho** [cnecrea/infpro#2]
As putea cumva sa vad in acelasi moment analiza datelor pentru inca un oras, fara sa schimb orasul in configurarea integrarii?

**Comment by cnecrea** [comment]
> As putea cumva sa vad in acelasi moment analiza datelor pentru inca un oras, fara sa schimb orasul in configurarea integrarii?




Salut,

Mulțumesc pentru întrebare! În acest moment, integrarea este concepută să monitorizeze doar epicentrul cutremurului și, eventual, un singur oraș, ceea ce consider că este relevant pentru majoritatea utilizatorilor. Totuși, pe viitor, dacă voi observa că această funcționalitate devine relevantă, cu siguranță voi lua în considerare implementarea ei.
